# Generated by Django 4.2 on 2023-06-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_message_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='age',
            new_name='birth_date',
        ),
    ]
