# Generated by Django 4.2 on 2023-08-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pictre',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
