# Generated by Django 4.2 on 2023-08-14 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_pictre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pictre',
            new_name='picture',
        ),
    ]
