# Generated by Django 4.2.1 on 2023-05-12 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='-', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='-', max_length=120)),
                ('job_title', models.CharField(default='-', max_length=120)),
                ('description', models.TextField()),
                ('salary', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jobs.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.profile')),
                ('requirements', models.ManyToManyField(to='jobs.requirements')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jobs.timetype')),
            ],
        ),
    ]
