# Generated by Django 4.2.1 on 2023-05-28 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_slug'),
        ('jobs', '0002_remove_job_title_alter_job_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jobs', to='users.profile'),
        ),
    ]
