# Generated by Django 4.2.1 on 2023-05-30 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_slug'),
        ('jobs', '0005_alter_job_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_answer', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('answer_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to='jobs.comment')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='users.profile')),
            ],
        ),
    ]
