# Generated by Django 4.2.1 on 2023-05-31 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='jobs.job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.ManyToManyField(blank=True, to='jobs.requirements'),
        ),
    ]
