# Generated by Django 4.2 on 2023-06-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_job_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Publish', 'Publish'), ('Not publish', 'Not publish')], default='Publish', max_length=50),
        ),
    ]
